import Head from 'next/head';
import React, { FC } from 'react';
import { CustomHeadProps } from '../../types/Component';

export const CustomHead: FC<CustomHeadProps> = ({ title = "threejs_sample", iconLink = "/favicon.ico" }) => {
    return (
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href={iconLink} />
        </Head>
    )
};
